FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build


FROM nginx:alpine

# Кладём билд Vite в стандартную папку nginx
COPY --from=builder /app/dist /usr/share/nginx/html