# Generated by Django 5.1.3 on 2025-05-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='og_site_name',
            field=models.CharField(default='og site name', max_length=120, verbose_name='Og:site_name'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='og_url',
            field=models.CharField(default='https://example.ru', max_length=30, verbose_name='Og:url'),
        ),
    ]
